import { useState } from 'react';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { Check, Database, Pencil, Plus, Tag, Trash2, X, ArrowLeft } from 'lucide-react';

const sessionDefaults = { certification_track_id: '', number: '', phase: 1, title: '', order: '', tag_ids: [], pass_score: 70, time_limit: 90, question_count: 25, is_open: false };
const examDefaults = { session_id: '', title: '', mode: 'practice', question_count: 25 };
const questionDefaults = { session_id: '', exam_id: '', content: '', tag_ids: [], options: JSON.stringify([{ key: 'A', text: '', is_correct: true }, { key: 'B', text: '', is_correct: false }], null, 2) };
const trackDefaults = { slug: '', title: '', description: '', is_active: true, cert_key: '', variant_label: '' };
const tagDefaults = { type: '', label: '' };

export default function Admin({ pending = [], sessions = [], events = [], report = {}, tracks = [], tags = [] }) {
  const [tab, setTab] = useState(() => new URLSearchParams(window.location.search).get('tab') || 'approvals');
  const [processingId, setProcessingId] = useState(null);
  const [editing, setEditing] = useState(null);
  const review = async (id, action) => {
    const note = action === 'reject' ? window.prompt('Reason for returning this submission:') : window.prompt('Optional approval note:');
    if (action === 'reject' && !note) return;
    setProcessingId(id);
    try {
      const xsrf = decodeURIComponent((document.cookie.match(/(?:^|; )XSRF-TOKEN=([^;]+)/) || [])[1] || '');
      const res = await fetch(`/admin/passimark/progress/${id}/${action}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Accept: 'application/json', 'X-Requested-With': 'XMLHttpRequest', 'X-XSRF-TOKEN': xsrf },
        credentials: 'same-origin',
        body: JSON.stringify({ note: note || '' }),
      });
      const data = await res.json().catch(() => ({}));
      window.alert(data.message || (res.ok ? 'Done.' : `Request failed (${res.status}).`));
    } catch (error) {
      window.alert('Network error — could not reach the server.');
    } finally {
      setProcessingId(null);
      router.reload({ only: ['pending', 'events', 'report'] });
    }
  };
  const remove = (type, id) => { if (window.confirm('Delete this content? This cannot be undone.')) router.delete(`/admin/${type}/${id}`, { preserveScroll: true }); };
  const exams = sessions.flatMap((session) => (session.exams || []).map((exam) => ({ ...exam, sessionTitle: session.title })));
  const questions = sessions.flatMap((session) => (session.questions || []).map((question) => ({ ...question, sessionTitle: session.title })));
  const items = tab === 'sessions' ? sessions : tab === 'exams' ? exams : tab === 'questions' ? questions : tab === 'tags' ? tags : tracks;
  const type = tab === 'sessions' ? 'sessions' : tab === 'exams' ? 'exams' : tab === 'questions' ? 'questions' : tab === 'tags' ? 'tags' : 'certification-tracks';
  return <><Head title="Admin Control Center" /><main className="min-h-screen bg-slate-950 px-6 py-8 text-white"><section className="mx-auto max-w-7xl space-y-6"><Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4" /> Back to dashboard</Link><header className="flex flex-col gap-4 border-b border-slate-800 pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-medium uppercase tracking-[0.2em] text-emerald-400">Operations</p><h1 className="mt-2 text-3xl font-bold">Passimark Control Center</h1><p className="mt-2 text-sm text-slate-400">Review learner progression and maintain assessment content.</p></div><div className="flex items-center gap-2 text-sm text-slate-400"><Database className="h-4 w-4" /> {sessions.length} sessions across {tracks.length} track{tracks.length === 1 ? '' : 's'} · {tags.length} tag{tags.length === 1 ? '' : 's'}</div></header><nav className="flex flex-wrap gap-2 border-b border-slate-800 pb-3">{[['approvals', 'Approvals'], ['tracks', 'Tracks'], ['sessions', 'Sessions'], ['exams', 'Exams'], ['questions', 'Questions'], ['tags', 'Tags']].map(([key, label]) => <button type="button" key={key} onClick={() => setTab(key)} className={`rounded-lg px-4 py-2 text-sm font-medium ${tab === key ? 'bg-emerald-500 text-slate-950' : 'text-slate-300 hover:bg-slate-800'}`}>{label}</button>)}</nav>{tab === 'approvals' ? <><ReportCards report={report} /><ApprovalQueue pending={pending} events={events} processingId={processingId} review={review} /></> : tab === 'tracks' ? <TracksPanel tracks={tracks} onAdd={() => setEditing(trackDefaults)} onEdit={setEditing} onDelete={(id) => remove('certification-tracks', id)} /> : tab === 'tags' ? <TagsPanel tags={tags} onAdd={() => setEditing(tagDefaults)} onEdit={setEditing} onDelete={(id) => remove('tags', id)} /> : <ContentPanel title={tab} type={type} items={items} onAdd={() => setEditing(type === 'sessions' ? sessionDefaults : type === 'exams' ? examDefaults : questionDefaults)} onEdit={setEditing} onDelete={remove} />}{editing && (type === 'sessions' ? <SessionForm value={editing} tracks={tracks} tags={tags} onClose={() => setEditing(null)} /> : type === 'exams' ? <ExamForm value={editing} sessions={sessions} onClose={() => setEditing(null)} /> : type === 'certification-tracks' ? <TrackForm value={editing} onClose={() => setEditing(null)} /> : type === 'tags' ? <TagForm value={editing} onClose={() => setEditing(null)} /> : <QuestionForm value={editing} sessions={sessions} tags={tags} onClose={() => setEditing(null)} />)}</section></main></>;
}
function ReportCards({ report }) { return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[['Learners', report.learners || 0], ['Attempts', report.attempts || 0], ['Completed', report.completed_attempts || 0], ['Average score', `${report.average_score || 0}%`], ['Pending', report.pending_approvals || 0]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-700 bg-slate-900 p-4"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-2xl font-semibold text-white">{value}</p></div>)}</div>; }
function ApprovalQueue({ pending, events, processingId, review }) { return <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><section><h2 className="text-xl font-semibold">Pending approvals <span className="text-sm text-slate-500">({pending.length})</span></h2>{pending.length === 0 && <p className="mt-4 rounded-xl border border-dashed border-slate-700 p-6 text-sm text-slate-400">No learner submissions need review.</p>}{pending.map((item) => <div key={item.id} className="mt-3 rounded-xl border border-slate-700 bg-slate-900 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{item.user?.name}</p><p className="text-sm text-slate-400">{item.session?.title} · Score {item.score}%</p></div><div className="flex gap-2"><button type="button" disabled={processingId === item.id} onClick={() => review(item.id, 'approve')} className="inline-flex items-center gap-1 rounded-lg bg-emerald-500 px-3 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50"><Check className="h-4 w-4" /> Approve</button><button type="button" disabled={processingId === item.id} onClick={() => review(item.id, 'reject')} className="rounded-lg bg-red-500 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Reject</button></div></div></div>)}</section><section><h2 className="text-xl font-semibold">Recent decisions</h2>{events.map((event) => <div key={event.id} className="mt-3 rounded-xl border border-slate-800 bg-slate-900 p-4 text-sm"><p className="capitalize text-white">{event.action}</p><p className="mt-1 text-slate-400">{event.progress?.user?.name} · {event.progress?.session?.title}</p>{event.note && <p className="mt-2 text-slate-500">{event.note}</p>}</div>)}</section></div>; }
function ContentPanel({ title, type, items, onAdd, onEdit, onDelete }) { const label = title.slice(0, -1); return <section><div className="flex items-center justify-between"><h2 className="text-xl font-semibold capitalize">{title} <span className="text-sm text-slate-500">({items.length})</span></h2><button type="button" onClick={onAdd} className="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2 text-sm font-semibold text-slate-950"><Plus className="h-4 w-4" /> Add {label}</button></div><div className="mt-4 grid gap-3 md:grid-cols-2">{items.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 rounded-xl border border-slate-700 bg-slate-900 p-4"><div className="min-w-0 space-y-1"><p className="line-clamp-2 font-medium text-white">{item.title || item.content || `${item.number}. Session`}</p><p className="text-xs text-slate-400">{item.sessionTitle || `Phase ${item.phase}`} {item.mode ? `· ${item.mode}` : ''}</p></div><div className="flex shrink-0 gap-1"><button type="button" title="Edit" onClick={() => onEdit(item)} className="rounded p-2 text-slate-400 hover:bg-slate-800 hover:text-white"><Pencil className="h-4 w-4" /></button><button type="button" title="Delete" onClick={() => onDelete(type, item.id)} className="rounded p-2 text-red-300 hover:bg-red-500/10"><Trash2 className="h-4 w-4" /></button></div></div>)}</div></section>; }
function TracksPanel({ tracks, onAdd, onEdit, onDelete }) { const categories = [...new Set((tracks || []).map((t) => t.cert_key || t.slug))].sort(); return <section><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Certification tracks <span className="text-sm text-slate-500">({tracks.length})</span></h2><button type="button" onClick={onAdd} className="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2 text-sm font-semibold text-slate-950"><Plus className="h-4 w-4" /> Add track</button></div><p className="mt-2 text-sm text-slate-400">A track is one bundle/variant under a certification category (<span className="font-mono text-emerald-300">cert_key</span>). Multiple bundles can share a category and land in their own rows automatically.</p><div className="mt-4 flex flex-wrap gap-2">{categories.map((key) => { const count = (tracks || []).filter((t) => (t.cert_key || t.slug) === key).length; return <span key={key} className={`rounded-full border px-3 py-1 text-xs ${count > 1 ? 'border-amber-500/40 bg-amber-500/10 text-amber-300' : 'border-slate-700 bg-slate-900 text-slate-300'}`}>{key} · {count} bundle{count > 1 ? 's' : ''}</span>; })}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{tracks.map((track) => <div key={track.id} className="flex items-center justify-between gap-4 rounded-xl border border-slate-700 bg-slate-900 p-4"><div className="min-w-0 space-y-1"><p className="font-medium text-white">{track.title} <span className="text-xs text-slate-500">({track.slug})</span></p><p className="text-xs text-slate-400">{[track.cert_key && track.cert_key !== track.slug ? track.cert_key : null, track.variant_label, track.is_active ? 'Active' : 'Inactive', track.source].filter(Boolean).join(' · ')} · {track.sessions_count ?? 0} sessions</p></div><div className="flex shrink-0 gap-1"><button type="button" title="Edit" onClick={() => onEdit(track)} className="rounded p-2 text-slate-400 hover:bg-slate-800 hover:text-white"><Pencil className="h-4 w-4" /></button><button type="button" title="Delete" onClick={() => onDelete(track.id)} className="rounded p-2 text-red-300 hover:bg-red-500/10"><Trash2 className="h-4 w-4" /></button></div></div>)}</div></section>; }
function TagsPanel({ tags, onAdd, onEdit, onDelete }) { const groups = ['domain', 'bloom', 'skill'].map((type) => ({ type, items: (tags || []).filter((t) => t.type === type) })); return <section><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Taxonomy tags <span className="text-sm text-slate-500">({(tags || []).length})</span></h2><button type="button" onClick={onAdd} className="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2 text-sm font-semibold text-slate-950"><Plus className="h-4 w-4" /> Add tag</button></div><p className="mt-2 text-sm text-slate-400">Tags are the real taxonomy behind the domain, Bloom level, and skill strings shared across sessions and questions.</p><div className="mt-4 grid gap-4 md:grid-cols-3">{groups.map(({ type, items }) => <section key={type} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="flex items-center gap-1.5 text-sm font-semibold capitalize text-slate-200"><Tag className="h-4 w-4" /> {type} <span className="text-xs text-slate-500">({items.length})</span></h3><div className="mt-3 space-y-2">{items.map((tag) => <div key={tag.id} className="flex items-center justify-between gap-3 rounded-lg border border-slate-700 bg-slate-950 p-3"><div className="min-w-0 space-y-0.5"><p className="truncate text-sm font-medium text-white">{tag.label}</p><p className="text-xs text-slate-500">{tag.slug} · {tag.questions_count ?? 0} questions · {tag.sessions_count ?? 0} sessions</p></div><div className="flex shrink-0 gap-1"><button type="button" title="Edit" onClick={() => onEdit(tag)} className="rounded p-1.5 text-slate-400 hover:bg-slate-800 hover:text-white"><Pencil className="h-4 w-4" /></button><button type="button" title="Delete" onClick={() => onDelete(tag.id)} className="rounded p-1.5 text-red-300 hover:bg-red-500/10"><Trash2 className="h-4 w-4" /></button></div></div>)}</div></section>)}</div></section>; }
function FormShell({ title, children, onClose }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-slate-700 bg-slate-900 p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button type="button" onClick={onClose} className="rounded p-2 text-slate-400 hover:bg-slate-800"><X className="h-5 w-5" /></button></div>{children}</div></div>; }
function Field({ label, children }) { return <label className="grid gap-2 text-sm text-slate-300">{label}{children}</label>; }
function Input({ value, onChange, type = 'text', required = false }) { return <input required={required} type={type} value={value ?? ''} onChange={onChange} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white outline-none focus:border-emerald-400" />; }
function Errors({ errors }) { return Object.values(errors || {}).length ? <div className="rounded-lg border border-red-500/40 bg-red-500/10 p-3 text-sm text-red-200">{Object.values(errors).map((error, index) => <p key={index}>{error}</p>)}</div> : null; }
function Buttons({ form, onClose }) { return <><Errors errors={form.errors} /><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-slate-700 px-4 py-2 text-sm text-slate-300">Cancel</button><button disabled={form.processing} className="rounded-lg bg-emerald-500 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">{form.processing ? 'Saving...' : 'Save'}</button></div></>; }
function TagPicker({ tags, value, onChange }) { const toggle = (id) => onChange(value.includes(id) ? value.filter((v) => v !== id) : [...value, id]); return <div className="flex flex-wrap gap-2">{(tags || []).map((tag) => { const active = value.includes(tag.id); return <button type="button" key={tag.id} onClick={() => toggle(tag.id)} className={`rounded-full border px-3 py-1 text-xs font-medium ${active ? 'border-emerald-400 bg-emerald-500/20 text-emerald-200' : 'border-slate-700 text-slate-400 hover:border-slate-500'}`}>{tag.label}</button>; })}</div>; }
function SessionForm({ value, tracks, tags, onClose }) { const form = useForm({ ...value, tag_ids: (value.tags || []).map((t) => t.id) }); const edit = Boolean(value.id); const domainTags = (tags || []).filter((t) => t.type === 'domain'); return <FormShell title={edit ? 'Edit session' : 'New session'} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); const options = { onSuccess: onClose }; edit ? form.put(`/admin/sessions/${value.id}`, options) : form.post('/admin/sessions', options); }} className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Certification track"><select required value={form.data.certification_track_id} onChange={(e) => form.setData('certification_track_id', e.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"><option value="">Choose a track</option>{tracks.map((track) => <option key={track.id} value={track.id}>{track.title}</option>)}</select></Field><Field label="Title"><Input required value={form.data.title} onChange={(e) => form.setData('title', e.target.value)} /></Field><Field label="Domain tags"><TagPicker tags={domainTags} value={form.data.tag_ids} onChange={(ids) => form.setData('tag_ids', ids)} /></Field><Field label="Number"><Input required type="number" value={form.data.number} onChange={(e) => form.setData('number', e.target.value)} /></Field><Field label="Phase"><Input required type="number" value={form.data.phase} onChange={(e) => form.setData('phase', e.target.value)} /></Field><Field label="Order"><Input required type="number" value={form.data.order} onChange={(e) => form.setData('order', e.target.value)} /></Field><Field label="Pass score"><Input type="number" value={form.data.pass_score} onChange={(e) => form.setData('pass_score', e.target.value)} /></Field><Buttons form={form} onClose={onClose} /></form></FormShell>; }
function ExamForm({ value, sessions, onClose }) { const form = useForm(value); const edit = Boolean(value.id); return <FormShell title={edit ? 'Edit exam' : 'New exam'} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); const options = { onSuccess: onClose }; edit ? form.put(`/admin/exams/${value.id}`, options) : form.post('/admin/exams', options); }} className="mt-6 grid gap-4"><Field label="Session"><select required value={form.data.session_id} onChange={(e) => form.setData('session_id', e.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"><option value="">Choose a session</option>{sessions.map((session) => <option key={session.id} value={session.id}>{session.number}. {session.title}</option>)}</select></Field><Field label="Title"><Input required value={form.data.title} onChange={(e) => form.setData('title', e.target.value)} /></Field><Field label="Mode"><select value={form.data.mode} onChange={(e) => form.setData('mode', e.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"><option value="practice">Practice</option><option value="timed">Timed</option><option value="cat">CAT</option></select></Field><Field label="Question count"><Input type="number" value={form.data.question_count} onChange={(e) => form.setData('question_count', e.target.value)} /></Field><Buttons form={form} onClose={onClose} /></form></FormShell>; }
function QuestionForm({ value, sessions, tags, onClose }) { const form = useForm({ ...value, tag_ids: (value.tags || []).map((t) => t.id), options: typeof value.options === 'string' ? value.options : JSON.stringify(value.options || [], null, 2) }); const edit = Boolean(value.id); const domainTags = (tags || []).filter((t) => t.type === 'domain'); return <FormShell title={edit ? 'Edit question' : 'New question'} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); let options; try { options = JSON.parse(form.data.options); } catch { form.setError('options', 'Options must be valid JSON.'); return; } form.transform(() => ({ ...form.data, options })); const request = { onSuccess: onClose }; edit ? form.put(`/admin/questions/${value.id}`, request) : form.post('/admin/questions', request); }} className="mt-6 grid gap-4"><Field label="Session"><select required value={form.data.session_id} onChange={(e) => form.setData('session_id', e.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"><option value="">Choose a session</option>{sessions.map((session) => <option key={session.id} value={session.id}>{session.number}. {session.title}</option>)}</select></Field><Field label="Question"><textarea required value={form.data.content} onChange={(e) => form.setData('content', e.target.value)} className="min-h-24 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white" /></Field><Field label="Domain tags"><TagPicker tags={domainTags} value={form.data.tag_ids} onChange={(ids) => form.setData('tag_ids', ids)} /></Field><Field label="Options JSON"><textarea required value={form.data.options} onChange={(e) => form.setData('options', e.target.value)} className="min-h-40 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 font-mono text-sm text-white" /></Field><Buttons form={form} onClose={onClose} /></form></FormShell>; }
function TrackForm({ value, onClose }) { const form = useForm(value); const edit = Boolean(value.id); return <FormShell title={edit ? 'Edit certification track' : 'New certification track'} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); const options = { onSuccess: onClose }; edit ? form.put(`/admin/certification-tracks/${value.id}`, options) : form.post('/admin/certification-tracks', options); }} className="mt-6 grid gap-4"><Field label="Title"><Input required value={form.data.title} onChange={(e) => form.setData('title', e.target.value)} /></Field><Field label="Slug"><Input required value={form.data.slug} onChange={(e) => form.setData('slug', e.target.value)} /></Field><Field label="Certification key (category)"><Input placeholder="e.g. cissp" value={form.data.cert_key} onChange={(e) => form.setData('cert_key', e.target.value)} /></Field><Field label="Variant label"><Input placeholder="e.g. Legacy v1" value={form.data.variant_label} onChange={(e) => form.setData('variant_label', e.target.value)} /></Field><Field label="Description"><textarea value={form.data.description} onChange={(e) => form.setData('description', e.target.value)} className="min-h-24 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white" /></Field><label className="flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={form.data.is_active} onChange={(e) => form.setData('is_active', e.target.checked)} className="h-4 w-4 accent-emerald-500" /> Active</label>{value.source && <p className="rounded-lg border border-slate-800 bg-slate-950 px-3 py-2 text-xs text-slate-500">Source: <span className="font-mono text-emerald-300">{value.source}</span> (managed by the system — seeds and package imports reuse this row by source).</p>}<Buttons form={form} onClose={onClose} /></form></FormShell>; }
function TagForm({ value, onClose }) { const form = useForm(value); const edit = Boolean(value.id); return <FormShell title={edit ? 'Edit tag' : 'New tag'} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); const options = { onSuccess: onClose }; edit ? form.put(`/admin/tags/${value.id}`, options) : form.post('/admin/tags', options); }} className="mt-6 grid gap-4 sm:grid-cols-2">{edit ? <Field label="Type"><p className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 capitalize text-slate-300">{form.data.type}</p></Field> : <Field label="Type"><select required value={form.data.type} onChange={(e) => form.setData('type', e.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"><option value="">Choose a type</option><option value="domain">Domain</option><option value="bloom">Bloom level</option><option value="skill">Skill</option></select></Field>}<Field label="Label"><Input required value={form.data.label} onChange={(e) => form.setData('label', e.target.value)} /></Field><Buttons form={form} onClose={onClose} /></form></FormShell>; }